export default [
  {
    userName: 'user1',
    isHost: false,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
  {
    userName: 'user2',
    isHost: false,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
  {
    userName: 'user3',
    isHost: false,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
  {
    userName: 'user4',
    isHost: true,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
  {
    userName: 'user5',
    isHost: false,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
  {
    userName: 'binimini',
    isHost: false,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
  {
    userName: 'user7',
    isHost: false,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
  {
    userName: 'user8',
    isHost: false,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
  {
    userName: 'user9',
    isHost: false,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
  {
    userName: 'user10',
    isHost: false,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
  {
    userName: 'user11',
    isHost: false,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
  {
    userName: 'user12',
    isHost: false,
    isReady: true,
    socketId: '?',
    isDead: false,
    voteFrom: [],
  },
];
